s10 <- read.csv("/work/dab118/WESAD/S10.csv")
s10$Condition <- factor(s10$Condition, labels = c("transient", "base", "stress", "amusement", "meditation", "NA", "NA", "NA"))
#print(dim(s10))
print("Summary of Subject 10")
print(summary(s10))
print("Correlation between Wrist and Chest Temp")
print(cor(s10$Ctemp, s10$Wtemp))
print("Mean of Chest Temp given Condition")
print("Stress:")
print(mean(s10$Ctemp[s10$Condition == "stress"]))
print("Meditation:")
print(mean(s10$Ctemp[s10$Condition == "meditation"]))
print("SD of Temp:")
print(sd(s10$Ctemp))